spring:
  cloud:
    config:
      server:
        git:
          uri: ${CA}/cloud-native-java
          search-paths:
          - config-service/config
server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false