server:
  port: 9191
management:
  server:
    servlet:x
      context-path: "/uaa"

logging:
  level: 
    org.springframework.security: DEBUG 

eureka:
  instance:
    hostname: localhost
  # client:
    # service-url: http://localhost:8761/eureka/
    # serviceUrl:
      # defaultZone: http://localhost:8761/eureka/

      
# eureka.instance.prefer-ip-address=true
# eureka.instance.ip-address=192.168.1.7

# spring.security.user.name=us 
# spring.security.user.password= {noop}pass

#security.oauth2.client.clientId: acme
#security.oauth2.client.clientSecret: acmesecret
#security.oauth2.client.authorized-grant-types: authorization_code,refresh_token,password
#security.oauth2.client.scope: openid
