server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    # enabled: false
      
      
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#spring.cloud.inetutils.preferredNetworks=192.168

